name: Comment on Pull request
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"body": "Thankyou for your contribution!"}' \
        https://api.github.com/repos/arathipremkumar2408/deveops_test/issues/$PR_NUMBER/comments
