name: Push to protected branch

on:
  workflow_dispatch

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Make changes
      run: |
        git config --global user.email "arathipremkumar2608@gmail.com"
        git config --global user.name "arathipremkumar2408"

        echo "New changes" >> changes.txt
        git add changes.text
        git commit -m "Add changes"

    - name: Push changes
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_PAT}}

      run:
        git push origin feature-branch
